In [1]:
import numpy as np
import pandas as pd
n1 = np.random.randint(50,100,size=(10,))

"""display(n1)
print(type(n1))"""
#s2=["Karl","Ken","Kent","Kev","Lee","Laurence","Leo","Leslie","Leon","Liam"]
#s1=pd.Series(n1,index=s2)
s1=pd.Series(n1,index=[f"學生{i+1}"for i in range(10)])

display(s1)
display(s1.values)
display(s1.index)

學生1     64
學生2     82
學生3     86
學生4     58
學生5     80
學生6     53
學生7     91
學生8     70
學生9     71
學生10    89
dtype: int64

array([64, 82, 86, 58, 80, 53, 91, 70, 71, 89])

Index(['學生1', '學生2', '學生3', '學生4', '學生5', '學生6', '學生7', '學生8', '學生9', '學生10'], dtype='object')

In [10]:
import requests
"""url = 'http://www.richyli.com/name/index.asp'
response = requests.get(url)
response.encoding  = 'big5'
result = response.text.splitlines()
names = result[114].split('、')
print(names[:3])
"""
def getname(num):
    times = 1
    cnames = []
    for i in range(times):
        url = 'http://www.richyli.com/name/index.asp'
        response = requests.get(url)
        response.encoding  = 'big5'
        result = response.text.splitlines()
        names = result[114].split('、')
    return names[:num]

name_lists = getname(100)

In [11]:
print(name_list)
name_list=['陳克以', '黃鈺薇', '陳百弘', '宋雅鈴', '林慧民', '楊瑩政', '黎明軒', '游慧萍', '陳惠茹', '張芸香', '黃建財', '王郁友', '陳志偉', '宋慧娟', '林易傑', '葉鈺雯', '陳欣娟', '郭詩珠', '張姿君', '蔡佩羽', '高麗雯', '邱俊吉', '舒怡婷', '陳倩春', '王皓婷', '李可元', '楊欣穎', '林逸男', '溫成凡', '溫健泉', '蕭雅云', '陳冠盛', '黃士瑋', '黃建怡', '潘欣潔', '楊佳燕', '劉世偉', '王明善', '張嘉航', '陳俊妤', '謝志峰', '張育茵', '潘耀然', '黃嬌群', '謝政勳', '張得航', '王晴宜', '傅佩芳', '屠允芝', '張志瑋', '陳家瑋', '張志茂', '鄭婉霞', '錢誠妏', '蔡育菁', '江孝雲', '葉婕妤', '吳佩全', '李宛淳', '沈琪峰', '林家賢', '林怡岳', '楊雅霞', '唐秀玲', '張為旺', '吳若樂', '姜佐友', '楊涵梅', '張凱年', '溫偉成', '陳中琴', '景竣航', '李博仁', '黃柏欣', '林妤馨', '張筱芸', '余文彬', '王惠玉', '李宣禮', '蔡幼偉', '林平芷', '陳胤一', '郭妤菱', '黃瑋婷', '簡幼仲', '黃雅雯', '吳政貴', '黃紀仰', '張紀善', '黃健平', '蔡淑芷', '伊秀玲', '馬佳蓉', '鄭冰強', '陳凱婷', '陳玉婷', '鄭馥易', '陳逸雲', '許馨文', '涂依中']

['陳克以', '黃鈺薇', '陳百弘', '宋雅鈴', '林慧民', '楊瑩政', '黎明軒', '游慧萍', '陳惠茹', '張芸香', '黃建財', '王郁友', '陳志偉', '宋慧娟', '林易傑', '葉鈺雯', '陳欣娟', '郭詩珠', '張姿君', '蔡佩羽', '高麗雯', '邱俊吉', '舒怡婷', '陳倩春', '王皓婷', '李可元', '楊欣穎', '林逸男', '溫成凡', '溫健泉', '蕭雅云', '陳冠盛', '黃士瑋', '黃建怡', '潘欣潔', '楊佳燕', '劉世偉', '王明善', '張嘉航', '陳俊妤', '謝志峰', '張育茵', '潘耀然', '黃嬌群', '謝政勳', '張得航', '王晴宜', '傅佩芳', '屠允芝', '張志瑋', '陳家瑋', '張志茂', '鄭婉霞', '錢誠妏', '蔡育菁', '江孝雲', '葉婕妤', '吳佩全', '李宛淳', '沈琪峰', '林家賢', '林怡岳', '楊雅霞', '唐秀玲', '張為旺', '吳若樂', '姜佐友', '楊涵梅', '張凱年', '溫偉成', '陳中琴', '景竣航', '李博仁', '黃柏欣', '林妤馨', '張筱芸', '余文彬', '王惠玉', '李宣禮', '蔡幼偉', '林平芷', '陳胤一', '郭妤菱', '黃瑋婷', '簡幼仲', '黃雅雯', '吳政貴', '黃紀仰', '張紀善', '黃健平', '蔡淑芷', '伊秀玲', '馬佳蓉', '鄭冰強', '陳凱婷', '陳玉婷', '鄭馥易', '陳逸雲', '許馨文', '涂依中']

In [12]:
import numpy as np
import pandas as pd

n2 = np.random.randint(50,100,size=(20,5))
dataFrame = pd.DataFrame(data=n2,
                         index=name_list[:20],
                         columns=["國文","英文","數學","自然","社會"]
             )
dataFrame

     國文  英文  數學  自然  社會
陳克以  63  93  87  86  74
黃鈺薇  75  76  70  83  71
陳百弘  53  91  95  56  78
宋雅鈴  82  89  84  96  52
林慧民  85  56  69  69  57
楊瑩政  65  77  89  69  86
黎明軒  51  52  55  77  53
游慧萍  56  66  58  63  67
陳惠茹  71  94  52  65  98
張芸香  91  83  67  91  67
黃建財  83  71  86  97  66
王郁友  62  83  90  96  71
陳志偉  53  93  97  60  94
宋慧娟  53  58  50  57  69
林易傑  55  76  88  95  73
葉鈺雯  54  84  68  88  92
陳欣娟  95  75  99  85  82
郭詩珠  50  90  90  75  50
張姿君  69  64  87  52  73
蔡佩羽  55  55  76  87  61

In [13]:
import numpy as np
import pandas as pd

print("國文分數:")
print(dataFrame["國文"])

國文分數:
陳克以    63
黃鈺薇    75
陳百弘    53
宋雅鈴    82
林慧民    85
楊瑩政    65
黎明軒    51
游慧萍    56
陳惠茹    71
張芸香    91
黃建財    83
王郁友    62
陳志偉    53
宋慧娟    53
林易傑    55
葉鈺雯    54
陳欣娟    95
郭詩珠    50
張姿君    69
蔡佩羽    55
Name: 國文, dtype: int64

In [14]:
import numpy as np
import pandas as pd
print("社會組分數")
socail_team = dataFrame["國文"]+dataFrame["社會"]+dataFrame["英文"]
dataFrame["社會組分數"]=socail_team
print(dataFrame["社會組分數"])

社會組分數
陳克以    230
黃鈺薇    222
陳百弘    222
宋雅鈴    223
林慧民    198
楊瑩政    228
黎明軒    156
游慧萍    189
陳惠茹    263
張芸香    241
黃建財    220
王郁友    216
陳志偉    240
宋慧娟    180
林易傑    204
葉鈺雯    230
陳欣娟    252
郭詩珠    190
張姿君    206
蔡佩羽    171
Name: 社會組分數, dtype: int64